name: Granja Animales Node.js CI  #(1)

on: #(2)
  push:
   branches:
      - main
      - feat-nuevoanimal
  pull_request:
    branches:
      - main
      - feat-nuevoanimal

jobs: #(3)
  build:

    runs-on: ubuntu-latest #(4)



    steps: #(5)

    - name: Checkout repository # (6)


      uses: actions/checkout@v2 #(7)









    - name: Use Node.js
      uses: actions/setup-node@v1 #(8)
      with:
        node-version: '18.x'






    - name: Run Yarn #(9)
      run: yarn
    - name: Run tests
      run: yarn test
